version: 0.12.{build}
skip_tags: true
image:
  - Ubuntu
  - Visual Studio 2019
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- ps: .\build.ps1 --target=Windows-Appveyor 
- sh: ./build.sh --target=Linux
test: off
before_deploy:
- ps: ${env:release_description} = ( Get-Content -LiteralPath BuildOutput/ReleaseNotes.txt -Encoding UTF8 ) -join "`n";
deploy:
- provider: GitHub
  tag: v$(APPVEYOR_BUILD_VERSION)
  description: $(release_description)
  auth_token:
    secure: lbPo8ff2MGNWqP7B4Agne9hz5ta0bTElGjUBVsz+MIRepZ/0mNJctNE4dY3CpiBS
  artifact: /^(?:(?![Ee]xperimental).)*$/
  draft: true
  force_update: true
  on:
    branch: master